Consider you're a python developer.Build a complete REST API for a to-do list task manager using Python with FastAPI. Follow these exact stages and checkpoints:

STAGE 0 — Hello Server
- Set up the project, install dependencies (fastapi, uvicorn), create a server running on localhost:8000.
- Add a GET / endpoint returning "Hello, Task API!".
- Verify with: curl -i http://localhost:8000/ → status 200.

STAGE 1 — Root and Health Endpoints
- GET / returns JSON: { "name": "Task API", "version": "1.0", "endpoints": ["/tasks"] }
- GET /health returns JSON: { "status": "ok" }
- Verify both with curl and browser.

STAGE 2 — Read Endpoints with 404
- Create an in-memory list with 3 pre-filled tasks: { id: 1, title: "Buy milk", done: false }, etc.
- GET /tasks returns the full list.
- GET /tasks/{id} returns one task.
- If id not found, return 404 with JSON: { "error": "Task 99 not found" }
- Verify: curl -i http://localhost:8000/tasks/1 → 200 + task; curl -i http://localhost:8000/tasks/99 → 404 + error.

STAGE 3 — Create with Validation
- POST /tasks accepts JSON body { "title": "Buy milk" }.
- Auto-assign next free id, set done: false, return 201 + the created task.
- If title is missing or empty, return 400 with error JSON.
- Verify: POST with valid title → 201; POST {} → 400.

STAGE 4 — Full CRUD (Update & Delete)
- PUT /tasks/{id} replaces title and/or done from request body. Return updated task. Unknown id → 404. Invalid body → 400.
- DELETE /tasks/{id} removes task. Return 204 (empty body). Unknown id → 404.
- Verify full cycle: create → update → mark done → delete → confirm with GET /tasks. All correct status codes.

STAGE 5 — Swagger UI
- Add one-line descriptions to each endpoint. Visit http://localhost:8000/docs (auto-generated by FastAPI).
- Verify: /docs shows all endpoints; "Try it out" works for full CRUD cycle.

STAGE 6 — GitHub Publish
- Initialize git, make ≥6 commits (one per stage).
- Create public GitHub repo, push code.
- Write README with: project description, install & run commands, endpoint table, one pasted curl -i output,

Give me the complete, working code for all stages, the exact commands to run, and the git commit history. Make it production-quality with proper error handling and status codes.
